import test from 'node:test';
import assert from 'node:assert/strict';
import {createApplication} from '../server.mjs';
import {hashPassword} from '../security.mjs';
import {recordStaffApplication} from '../staff-applications.mjs';

test('teams and assignments enforce roles, service match, overlap and persistence',async t=>{
  const {server,db}=await createApplication({filename:':memory:'});await new Promise(r=>server.listen(0,'127.0.0.1',r));
  t.after(async()=>{await new Promise(r=>server.close(r));db.close();});
  const origin='http://127.0.0.1:'+server.address().port;
  const hash=await hashPassword('Example-Password!123');for(const role of ['owner','admin'])db.prepare('INSERT INTO admins VALUES(?,?,?,?,?,1)').run(role,role+'@example.invalid',role,hash,role);
  let cookie='',csrf='';const call=async(path,data)=>{const r=await fetch(origin+'/api/'+path,{method:data?'POST':'GET',headers:{Cookie:cookie,...(data?{Origin:origin,'Content-Type':'application/json','X-CSRF-Token':csrf}:{})},body:data?JSON.stringify(data):undefined});return {r,data:await r.json()};};
  const login=async role=>{cookie='';csrf=(await call('session')).data.csrf;const result=await call('login',{email:role+'@example.invalid',password:'Example-Password!123'});cookie=result.r.headers.get('set-cookie').split(';')[0];csrf=(await call('session')).data.csrf;};
  await login('admin');assert.equal((await call('teams')).r.status,403);assert.equal((await call('staff-schedule')).r.status,403);
  assert.equal((await call('account_reports')).r.status,403);
  for(const path of ['audit','invoices','documents','documents/private','staff-hr?id=anything'])assert.equal((await call(path)).r.status,403);
  assert.equal((await call('staff-hr',{id:'anything'})).r.status,403);
  assert.equal((await call('documents',{title:'Not allowed'})).r.status,403);
  await login('owner');const input={team:'cleaners',name:'Sample Cleaner',email:'cleaner@example.invalid',reason:'Testing team setup'};
  assert.equal((await call('teams',input)).r.status,403);
  const applicationId=recordStaffApplication(db,{...input,service:'cleaning',jobTitle:'Cleaner'});
  assert.equal((await call('teams?team=cleaners')).data.rows.length,0);
  await login('admin');assert.equal((await call('approvals/'+applicationId,{status:'approved',expectedStatus:'pending',reason:'Reviewed application'})).r.status,403);await login('owner');
  assert.equal((await call('approvals/'+applicationId,{status:'approved',expectedStatus:'pending',reason:'Reviewed application'})).r.status,200);
  const id=db.prepare('SELECT member_id FROM staff_applications WHERE approval_id=?').get(applicationId).member_id;
  assert.equal((await call('approvals/'+applicationId,{status:'approved',expectedStatus:'pending',reason:'Repeated approval'})).r.status,409);
  assert.equal((await call('users')).data.rows[0].last_online,null);
  assert.equal((await call('users')).data.rows[0].kind,'staff_cleaning');
  assert.equal((await call('teams?team=all')).data.rows.length,1);
  const hr={id,version:0,job_title:'Cleaner',start_date:'2026-10-08',emergency_contact:'Fictional contact',notes:'Private QA note',extra:{phone:'TEST ONLY',dbs:'Not assessed'}};
  assert.equal((await call('staff-hr',hr)).r.status,200);
  assert.equal((await call('staff-hr?id='+id)).data.row.extra.phone,'TEST ONLY');
  assert.equal((await call('staff-hr',hr)).r.status,409);
  assert.ok(!JSON.stringify((await call('teams?team=all')).data).includes('TEST ONLY'));
  assert.ok(!JSON.stringify(db.prepare("SELECT * FROM audit WHERE resource='staff_hr'").all()).includes('Private QA note'));
  const doc=await call('documents',{title:'Test insurance',category:'insurance',expires_on:'',filename:'test.pdf',base64:Buffer.from('%PDF-1.4\n%%EOF').toString('base64')});assert.equal(doc.r.status,201);
  assert.equal((await call('documents?category=insurance')).data.total,1);
  assert.equal((await call('documents?category=invoice')).data.total,0);
  assert.equal((await call('teams/areas',{id,areas:'E14, Stratford'})).r.status,200);
  assert.equal((await call('teams?team=cleaners')).data.rows.length,1);
  for(const [key,service] of [['one','cleaning'],['two','cleaning'],['three','moving']])db.prepare('INSERT INTO bookings VALUES(?,?,?,?,?,?,?)').run(key,key,'Sample Student',service,'pending',0,new Date().toISOString());
  const assignment={memberId:id,bookingId:'one',start:'2026-10-20T09:00:00Z',end:'2026-10-20T11:00:00Z',reason:'Area and team checked'};
  assert.equal((await call('staff-schedule',assignment)).r.status,200);
  assert.equal((await call('staff-schedule',{...assignment,bookingId:'two'})).r.status,409);
  assert.equal((await call('staff-schedule',{...assignment,bookingId:'three'})).r.status,400);
  assert.equal((await call('staff-schedule')).data.rows[0].name,'Sample Cleaner');
  assert.equal((await call('staff-schedule?from=2026-10-20T10:00:00Z&to=2026-10-21T00:00:00Z')).data.rows.length,1);
  assert.equal((await call('staff-schedule?from=2026-10-20T11:00:00Z&to=2026-10-21T00:00:00Z')).data.rows.length,0);
  assert.equal((await call('staff-schedule?from=bad&to=2026-10-21')).r.status,400);
  const holiday=await call('staff-holidays',{memberId:id,startDate:'2026-10-22',endDate:'2026-10-23'});assert.equal(holiday.r.status,201);
  assert.equal((await call('staff-holidays',{memberId:id,startDate:'2026-10-20',endDate:'2026-10-20'})).r.status,409);
  const blocked={...assignment,start:'2026-10-22T09:00:00Z',end:'2026-10-22T11:00:00Z'};
  assert.equal((await call('staff-schedule',blocked)).r.status,409);
  const availability=await call('staff-availability?'+new URLSearchParams({bookingId:'one',start:blocked.start,end:blocked.end}));assert.equal(availability.data.rows[0].available,false);assert.equal(availability.data.rows[0].reason,'On holiday');
  assert.equal((await call('staff-holidays',{id:holiday.data.id})).r.status,200);
  assert.equal((await call('staff-availability?'+new URLSearchParams({bookingId:'one',start:blocked.start,end:blocked.end}))).data.rows[0].available,true);
  await call('teams',{id,status:'deactivated',reason:'Test deactivation'});
  assert.equal((await call('staff-schedule',assignment)).r.status,400);
  assert.equal(db.prepare('SELECT count(*) n FROM booking_assignments').get().n,1);
  db.prepare("UPDATE bookings SET status='confirmed' WHERE id='one'").run();
  const completed=await call('bookings/one/complete',{expectedStatus:'confirmed',reason:'Service finished successfully'});assert.equal(completed.r.status,200);assert.match(completed.data.invoice.reference,/^UM-INV-\d{4}-000001$/);
  const repeated=await call('bookings/one/complete',{expectedStatus:'confirmed',reason:'Retry completion request'});assert.equal(repeated.data.invoice.id,completed.data.invoice.id);
  assert.equal((await call('invoices')).data.total,1);
  assert.equal((await call('invoices/'+completed.data.invoice.id,{status:'paid',reason:'Payment verified externally'})).r.status,200);
  assert.equal((await call('invoices?status=paid')).data.total,1);
  assert.equal((await call('invoices')).data.outstanding_pence,0);
  await login('admin');assert.equal((await call('invoices/'+completed.data.invoice.id)).r.status,403);assert.equal((await call('bookings/one/complete',{expectedStatus:'confirmed',reason:'Attempt normal admin'})).r.status,403);
});
